= goos
:project-full-path: rhaendel/goos
:github-branch: master

image:https://travis-ci.org/{project-full-path}.svg?branch={github-branch}["Build Status", link="https://travis-ci.org/{project-full-path}"]
image:https://coveralls.io/repos/{project-full-path}/badge.svg?branch={github-branch}&service=github["Coverage Status", link="https://coveralls.io/github/{project-full-path}?branch={github-branch}"]


Growing Object-Oriented Software Guided by Tests - Coding along the lines of the book's example

This project follows the example developed in the book http://www.growing-object-oriented-software.com/[Growing Object-Oriented Software Guided by Tests]
by Steve Freeman and Nat Pryce.


== Prerequisites

The book's example code doesn't need a higher version than Java 6. But sometimes I make use of Java 7 features.
Hence, a Java JDK or JRE version 7 is needed. All further java dependencies (libraries needed at compile time, at
test time and at runtime) are managed and downloaded automatically by https://gradle.org/[Gradle].

The https://en.wikipedia.org/wiki/Openfire[Openfire] server is assumed to be "already there".
The GitHub project https://github.com/thilomack/goos-infra[thilomack/goos-infra] downloads and installs
an Openfire server as a docker container and configures it suitable for the book's example.

On Linux machines, only:

For running all tests on a continuous integration server, `setup_openfire.sh` downloads, installs and
configures an Openfire server locally. If a server is already there, the shell script just starts it.


== Generate Eclipse Project

Eclipse is my IDE of choice but this project doesn't stick to it.

Simply use

  ./gradlew eclipse

to generate Eclipse project and classpath files. If you want to use another IDE, feel free to apply
another plugin in `build.gradle` in the project's root.


== Build and run all (but one) Tests

At the current stage of following the book, there are two kinds of tests: End-to-end acceptance tests and unit tests.

The task

  ./gradlew build

compiles, builds and runs all tests. At first, it runs all unit tests. If and only if they pass, the integration tests run.
If in turn the latter pass, the end-to-end tests are executed.

== Run a special Group of Tests

Execute just the unit tests:

  ./gradlew test

Execute all integration tests:

  ./gradlew integrationTest

Execute all end-to-end tests:

  ./gradlew endtoendTest


=== The failing one

The one failing end-to-end test that drives development (-> ATDD, Acceptance Test Driven Development) can be
run using:

  ./gradlew endtoendFailingTest

It is excluded from continuous integration builds.


== Code Coverage

For calculating code coverage of all unit tests, using http://www.eclemma.org/jacoco/[JaCoCo], run:

  ./gradlew test jacocoTestReport
