= goos
:project-full-path: rhaendel/goos
:github-branch: master

image:http://img.shields.io/travis/{project-full-path}/{github-branch}.svg["Build Status", link="https://travis-ci.org/{project-full-path}"]
image:http://img.shields.io/coveralls/{project-full-path}/{github-branch}.svg["Coverage Status", link="https://coveralls.io/r/{project-full-path}"]

Growing Object-Oriented Software Guided by Tests - Coding along the lines of the book's example

This project follows the example developed in the book http://www.growing-object-oriented-software.com/[Growing Object-Oriented Software Guided by Tests]
by Steve Freeman and Nat Pryce.


== Prerequisites

The book's example code doesn't need a higher version than Java 6. But sometimes I make use of Java 8 features.
Hence, a JDK version 8 is needed. All further java dependencies (libraries needed at compile time, at
test time and at runtime) are managed and downloaded automatically by https://gradle.org/[Gradle].

The https://en.wikipedia.org/wiki/Openfire[Openfire] server is assumed to be "already there".
The GitHub project https://github.com/thilomack/goos-infra[thilomack/goos-infra] downloads and installs
an Openfire server as a docker container and configures it suitable for the book's example.

On Linux machines, only:

For running all tests on a continuous integration server, `setup_openfire.sh` downloads, installs and
configures an Openfire server locally. If a server is already there, the shell script just starts it.


== Import to your IDE

Eclipse and IntelliJ IDEA are able to import Gradle projects without any additional plugin applied to the Gradle build file.


== Build and run all Tests

The build distinguishes between three different kinds of tests:

* Unit tests: Very fast running tests that handle a single aspect (= a single class).
  They are executed together with the `compile` task using:

  ./gradlew build

and, however, can be run separately with:

  ./gradlew test

* End-to-end tests: Acceptance tests that once have driven development and now have to stay stable. They are designed to
  be as much end-to-end as possible, drive the UI directly and go through the whole stack, down to the Openfire chat server.
  They are run with the command:

  ./gradlew endtoendTest

* Integration tests: This level of testing lies in between of unit tests and end-to-end tests. It tests the integration
  of several classes.

  ./gradlew integrationTest

* The test that drives development: A single end-to-end test which fails until the new feature is finally developed and
  the test moves over to the other end-to-end tests. It is not part of the CI build and intended to run locally, only:

  ./gradlew endtoendFailingTest
